#
# Secret Manager, and the Workload Identity bindings that let pods read it.
#
# Every value here is generated by Terraform. None is ever supplied by hand,
# printed to a terminal, or committed. The managed Secret Manager CSI component
# mounts them into pods as files at runtime.
#
# One secret per value, rather than the two JSON documents the AWS stack used.
# The GKE SecretProviderClass provider maps one resourceName to one file path
# and has no JMESPath equivalent, so JSON would need either an init container
# with jq to split it or a change to the application's config loader. Since
# resourceName and path are independent, secret ids can be kebab-case while the
# mounted filenames stay exactly as the application expects them — which is
# what keeps backend/src/config/index.ts unchanged.
#
# Two things that improve on the AWS version as a side effect:
#
#   * IAM is per-secret, so the migration hook is granted the seven values it
#     actually needs rather than everything. Previously both roles shared one
#     policy covering both JSON blobs.
#   * Secret Manager deletes immediately with no recovery window, so the
#     recovery_window_in_days = 0 workaround has no counterpart here. Do not
#     set version_destroy_ttl on these — that is the opt-in feature which would
#     reintroduce exactly the "name still reserved tomorrow" problem.
#
data "google_project" "this" {}

resource "random_password" "jwt_access" {
  length  = 64
  special = false
}

resource "random_password" "jwt_refresh" {
  length  = 64
  special = false
}

# Seed account passwords. These log in to the demo storefront, so they are
# generated rather than left at the development defaults baked into the image.
resource "random_password" "seed_admin" {
  length  = 24
  special = false
}

resource "random_password" "seed_customer" {
  length  = 24
  special = false
}

locals {
  secret_prefix = "${var.project}-${var.environment}"

  # Keys are the filenames the pod sees under SECRETS_DIR. They are a contract
  # with three consumers and must not change casually:
  #   backend/src/config/index.ts        reads DB_*, JWT_*
  #   helm/.../migration.yaml            cats DB_* and SEED_* in shell
  #   backend/src/seed.ts                reads SEED_*
  secrets = {
    DB_USER     = var.db_username
    DB_PASSWORD = random_password.db.result
    DB_HOST     = google_compute_address.db.address
    DB_PORT     = "5432"
    DB_NAME     = var.db_name

    JWT_ACCESS_SECRET  = random_password.jwt_access.result
    JWT_REFRESH_SECRET = random_password.jwt_refresh.result

    SEED_ADMIN_PASSWORD    = random_password.seed_admin.result
    SEED_CUSTOMER_PASSWORD = random_password.seed_customer.result
  }

  # The migration Job assembles a DATABASE_URL and seeds accounts. It has no
  # business reading the JWT signing keys.
  migrate_secrets = [
    "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT", "DB_NAME",
    "SEED_ADMIN_PASSWORD", "SEED_CUSTOMER_PASSWORD",
  ]

  # Workload Identity Federation is enabled by default on Autopilot, and the
  # managed CSI component authenticates as the pod's own Kubernetes service
  # account. There is therefore no Google service account to create and no
  # annotation to put on the KSA — IAM binds directly to the federated
  # principal. This is what replaced the whole of iam-irsa.tf.
  wi_pool = "principal://iam.googleapis.com/projects/${data.google_project.this.number}/locations/global/workloadIdentityPools/${var.project_id}.svc.id.goog/subject/ns/${var.k8s_namespace}/sa"

  app_principal     = "${local.wi_pool}/${var.project}"
  migrate_principal = "${local.wi_pool}/${var.project}-migrate"
}

resource "google_secret_manager_secret" "this" {
  for_each = local.secrets

  secret_id = "${local.secret_prefix}-${lower(replace(each.key, "_", "-"))}"

  replication {
    auto {}
  }

  labels = {
    project     = var.project
    environment = var.environment
  }
}

resource "google_secret_manager_secret_version" "this" {
  for_each = local.secrets

  secret      = google_secret_manager_secret.this[each.key].id
  secret_data = each.value
}

# ------------------------------------------------------------------- access

# The depends_on is load-bearing and cannot be inferred.
#
# The principal:// strings are built from variables, not from the cluster
# resource, so Terraform sees no relationship and schedules these in parallel
# with cluster creation. But the Workload Identity pool <project>.svc.id.goog
# is created *by* the cluster, so the bindings race a ten-minute create and
# lose, failing with:
#
#   Error 400: Identity Pool does not exist (<project>.svc.id.goog)
#
# which reads like a configuration error rather than an ordering one. A second
# apply then succeeds, because by that point the cluster exists — the worst
# kind of bug, since it looks transient.
resource "google_secret_manager_secret_iam_member" "app" {
  for_each = google_secret_manager_secret.this

  secret_id = each.value.id
  role      = "roles/secretmanager.secretAccessor"
  member    = local.app_principal

  depends_on = [google_container_cluster.main]
}

resource "google_secret_manager_secret_iam_member" "migrate" {
  for_each = toset(local.migrate_secrets)

  secret_id = google_secret_manager_secret.this[each.key].id
  role      = "roles/secretmanager.secretAccessor"
  member    = local.migrate_principal

  depends_on = [google_container_cluster.main]
}
